### ISSUE TITLE
Code generation creates a class with suffix number for each reference to the same object.

### ISSUE THREAD

**Issue by arpel4** [pwall567/json-kotlin-schema-codegen#4] opened 2021-08-11 13:10 UTC
Hi,

Good job with this tool. Why code generation creates two classes with suffix number if the reference is pointing to the same object?. Which is the reason?.

Also if would like to use other numeric data types like BigInt in our generated classes what would you suggest to do?

following this json example:

```javascript
{
  "$schema": "http://json-schema.org/draft/2019-09/schema",
  "$id": "http://pwall.net/test",
  "title": "Product",
  "type": "object",
  "required": ["id", "name", "price"],
  "properties": {
    "id": {
      "type": "number",
      "description": "Product identifier"
    },
    "name": {
      "type": "string",
      "description": "Name of the product"
    },
    "price": {
      "type": "number"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "stock": {
      "$ref": "#/definitions/Test"
    },
    "stock2": {
      "$ref": "#/definitions/Test"
    }
  },
  "definitions": {
    "Test": {
      "type": "object",
      "properties": {
        "warehouse": {
          "type": "number"
        },
        "retail": {
          "type": "number"
        }
      }
    }
  }
}
```

output:

```
package com.app

import java.math.BigDecimal

data class Test(
    /** Product identifier */
    val id: BigDecimal,
    /** Name of the product */
    val name: String,
    val price: BigDecimal,
    val tags: List<String>? = null,
    val stock: Test? = null,
    val stock2: Test1? = null
) {

    data class Test(
        val warehouse: BigDecimal? = null,
        val retail: BigDecimal? = null
    )

    data class Test1(
        val warehouse: BigDecimal? = null,
        val retail: BigDecimal? = null
    )

}
```

Thanks,

Arturo

**Comment by pwall567** [comment] 2021-08-12 12:08
Hi Arturo, thanks for pointing this out.

I agree, the code generator should detect re-use of the same definition and use the same class.  I have a fix for this and I will get it into the code in the next day or two.

The second question - the use of other generated types - is already handled.  The code generator has the concept of "custom classes", which allow users to specify existing classes for specified types.  A common use is for Money types - many people have existing classes that represent money values and they want to specify them to the code generator.

There are three ways of doing this.

The first is to add a custom element to the schema, for example:
```
    "price": {
      "type": "number",
      "x-custom-type": "money"
    },
```
Then you add the following line just before `codeGenerator.generate(...)`:
```
        codeGenerator.addCustomClassByExtension("x-custom-type", "money", "BigInteger", "java.math")
```
You can have several combinations of extension id and value, and they may be used repeated times in the schema.  Obviously, you can use a system class or one of your own classes, specifying the class name and package.

The second technique is to use a custom "format" keyword (this is allowed by the JSON Schema specification).  In this case, you could use:
```
    "price": {
      "type": "number",
      "format": "bigint"
    },
```
And to specify this to the code generator:
```
        codeGenerator..addCustomClassByFormat("bigint", ClassName("BigInteger", "java.math"))
```
(I apologise for the inconsistent way of specifying the custom class; I will clean this up shortly :smile: )

In some cases it will not be possible or desirable to modify the schema in this way, so the third option allows for a custom class to be specified by its location in the schema.  If you add the following line:
```
        codeGenerator.addCustomClassByURI(URI("http://pwall.net/test#/properties/price"), ClassName("BigInteger", "java.math"))
```
The code generator will intercept that one instance identified by the URI (taking the base URI from the `$id` of the schema and using the URI fragment id - the portion after the '#' - as a JSON Pointer) and substitute the custom class.

This last approach has the advantage that it doesn't require modification to the original schema, but it only covers a single case and must be specified repeatedly for each time it is required.

Your question makes me realise I need to document this functionality.  I'll try to get onto that shortly, but in the meantime I hope this helps.

Regards,
Peter

**Comment by arpel4** [comment] 2021-08-13 08:30
Great to hear 😊 .  thank you.

**Comment by pwall567** [comment] 2021-08-13 13:30
OK, there's a new version - 0.35 - deployed today containing the change to the creation of nested classes for "$ref" references.

I have also tidied up the function calls for custom classes - you can now use either form of class description with any of the custom class types.  Your IDE should show the parameter types required.

I hope these changes address your issues.

**Comment by arpel4** [comment] 2021-08-16 09:48
working fine 👍 . thanks.

**Comment by pwall567** [comment] 2021-08-16 14:20
Good to hear

**Comment by RuiLoureiro** [comment] 2022-01-05 09:30
I believe this is still happening in version `0.66`, generating the code using the schema provided by @arpel4, the output is:
```kotlin
package com.app

import java.math.BigDecimal

data class Test(
    /** Product identifier */
    val id: BigDecimal,
    /** Name of the product */
    val name: String,
    val price: BigDecimal,
    val tags: List<String>? = null,
    val stock: Stock? = null,
    val stock2: Stock2? = null
) {

    data class Stock(
        val warehouse: BigDecimal? = null,
        val retail: BigDecimal? = null
    )

    data class Stock2(
        val warehouse: BigDecimal? = null,
        val retail: BigDecimal? = null
    )

}
```

**Comment by pwall567** [comment] 2022-01-05 11:54
Hi - thanks for raising this issue.

I think your problem may be caused by the `nestedClassNameOption` setting.

This option is described in [the documentation on the Config file](https://github.com/pwall567/json-kotlin-schema-codegen/blob/main/CONFIG.md#nestedclassnameoption). The code generator has to choose the name to use for nested classes, and there are two options outlined in the documentation.

Confusingly, the two plugins use the default value of "property" (that's the value in the config file, in code it is `CodeGenerator.NestedClassNameOption.USE_NAME_FROM_PROPERTY`), while using the generator from Kotlin code, the default is "refSchema" (`CodeGenerator.NestedClassNameOption.USE_NAME_FROM_REF_SCHEMA`).

I think you must be using "property" (possibly as a result of using the plugin), in which case the generator chooses the names "Stock" and "Stock2" derived from the property names "stock" and "stock2" - they look different, so it generates separate classes.

The solution discussed earlier only works if the generator is using the "refSchema" option - the two properties refer to the same schema so they use the same nested class.  Can you try using the "refSchema" setting?  If you are using one of the plugins, I hope the documentation is sufficient to explain how to do this.

I apologise for the confusion - the first users of the plugin preferred the default setting of "property" and I didn't properly explain this in the documentation.

Regards,
Peter

**Comment by RuiLoureiro** [comment] 2022-01-05 12:58
Thank you for the quick and comprehensive reply!
I am indeed using the gradle plugin. As you suggested, I added a `codegen-config.json` file with `"nestedClassNameOption": "refSchema"`, and it works fine for the example above. However, if the `Stock` class is an array, it no longer works. In this case, the schema is:
```json
{
  "$schema": "http://json-schema.org/draft/2019-09/schema",
  "$id": "http://pwall.net/test",
  "title": "Product",
  "type": "object",
  "required": ["id", "name", "price"],
  "properties": {
    "id": {
      "type": "number",
      "description": "Product identifier"
    },
    "name": {
      "type": "string",
      "description": "Name of the product"
    },
    "price": {
      "type": "number"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "stock": {
      "$ref": "#/definitions/Test"
    },
    "stock2": {
      "$ref": "#/definitions/Test"
    }
  },
  "definitions": {
    "Test": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "warehouse": {
            "type": "number"
          },
          "retail": {
            "type": "number"
          }
        }
      }
    }
  }
}
```
and the output:
```kotlin
package com.app

import java.math.BigDecimal

data class Test(
    /** Product identifier */
    val id: BigDecimal,
    /** Name of the product */
    val name: String,
    val price: BigDecimal,
    val tags: List<String>? = null,
    val stock: List<Stock>? = null,
    val stock2: List<Stock2>? = null
) {

    data class Stock(
        val warehouse: BigDecimal? = null,
        val retail: BigDecimal? = null
    )

    data class Stock2(
        val warehouse: BigDecimal? = null,
        val retail: BigDecimal? = null
    )

}
```

**Comment by RuiLoureiro** [comment] 2022-01-05 13:09
Thank you for the quick and comprehensive reply!
I am indeed using the gradle plugin. As you suggested, I set `nestedClassNameOption` to "refSchema".
It works on the example above. However, if `Test` is an array, instead of an object, it no longer works.
In this case, the schema is:
```json
{
  "$schema": "http://json-schema.org/draft/2019-09/schema",
  "$id": "http://pwall.net/test",
  "title": "Product",
  "type": "object",
  "required": ["id", "name", "price"],
  "properties": {
    "id": {
      "type": "number",
      "description": "Product identifier"
    },
    "name": {
      "type": "string",
      "description": "Name of the product"
    },
    "price": {
      "type": "number"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "stock": {
      "$ref": "#/definitions/Test"
    },
    "stock2": {
      "$ref": "#/definitions/Test"
    }
  },
  "definitions": {
    "Test": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "warehouse": {
            "type": "number"
          },
          "retail": {
            "type": "number"
          }
        }
      }
    }
  }
}
```
and the output:
```kotlin
package com.app

import java.math.BigDecimal

data class Test(
    /** Product identifier */
    val id: BigDecimal,
    /** Name of the product */
    val name: String,
    val price: BigDecimal,
    val tags: List<String>? = null,
    val stock: List<Stock>? = null,
    val stock2: List<Stock2>? = null
) {

    data class Stock(
        val warehouse: BigDecimal? = null,
        val retail: BigDecimal? = null
    )

    data class Stock2(
        val warehouse: BigDecimal? = null,
        val retail: BigDecimal? = null
    )

}
```

**Comment by pwall567** [comment] 2022-01-06 12:22
OK, that definitely looks like a case that hasn't been covered correctly.

I think I can see a fix for this, but I'd like to take another day or so to think through the implications - whether modifying this will cause other problems.

I'll get back to you shortly...

**Comment by pwall567** [comment] 2022-01-07 12:19
I think I have fixed this issue - I would appreciate it if you would try version 0.67 and let me know if it resolves your issue.

And a side-effect of fixing this is that the generator will now recognise the repeat use by `$ref` of the same sub-schema even when used with the `nestedClassNameOption` of `property`.

Thanks for notifying me of the issue, and for providing such a clear report of the circumstances.

**Comment by RuiLoureiro** [comment] 2022-01-09 21:28
Thank you @pwall567 for such a fast fix, I can confirm that it is working for me!

**Comment by pwall567** [comment] 2022-01-09 22:45
Good to hear!

**Closed by pwall567** 2022-01-09 22:45 UTC
