### ISSUE TITLE
Problem with nesting and annotations

### ISSUE THREAD

**Issue by Christian-Schroeder79** [pwall567/json-kotlin-schema-codegen#29] opened 2023-05-23 09:19 UTC
Hi Peter,

first of all thank you for your great tool for generating kotlin data classes. I have a little problem using it atm. My Use Case is:

I want to use the maven plugin for generating kotlin data classes, which I can use together with kotlinx-serialization.

So I will need to annotate them. I found out how to do it with the config file (also great documentation btw.). 

BUT The nested classes are not annotated and I don't know how to get the Plugin to not nest those (as they are liked via $ref). So I would need either a possibility to not nest (maybe by defining a sequence in the pom file?, or having a flag "nesting") or to annotate all nested classes as well.

Do you have a hint for me how to achieve this?

Regards and all the best

Christian

**Comment by volkert-fastned** [comment] 2023-09-08 17:19
@pwall567 I ran into this exact same issue today. Indeed, the "main" class of each schema gets correctly annotated when configured properly in the JSON file, but the inner classes derived from the definitions in each schema do not.

This causes the compilation to fail, since the Kotlin Serialization Plugin needs each type (including that of any variables of annotated data classes) to be annotated as well.

Can you maybe look into this? Thanks.

**Comment by pwall567** [comment] 2023-09-17 14:27
I apologise (particularly to @Christian-Schroeder79 who has been waiting for 4 months) for not picking this up sooner.

It turned out to be a bit more complicated that I had expected, but version 0.94 should resolve this issue.  Please give it a try and let me know.

**Comment by volkert-fastned** [comment] 2023-09-17 23:45
@pwall567 I can confirm that your `0.94` fix indeed works, at least in my project. 👍🏽

I had a temporary workaround in the Gradle build file to replace any occurrences of the indented string `"    data class"` with `"    @Serializable data class"`. Crude, but it worked, until your fix came in, after which the duplicate annotations caused compilation errors again. After I removed my workarond, everything worked again. 😅

Good job! Thanks.

**Comment by pwall567** [comment] 2023-09-18 02:51
Pleased to hear it, and thanks for the rapid feedback.

I'll close this issue; if anyone has a related problem please open a new issue.

**Closed by pwall567** 2023-09-18 02:51 UTC
