### ISSUE TITLE
[0.81] Annotations config not being applied to generation of data classes

### ISSUE THREAD

**Issue by Tzrlk** [pwall567/json-kotlin-schema-codegen#16] opened 2022-09-30 22:02 UTC
When I have the following annotation config:
```json
"annotations": {
	"classes": {
		"kotlinx.serialization.Serializable": null,
		"javax.annotation.Generated": "\"{{&generator}}\", date=\"{{&dateTime}}\""
	}
},
```
the generated classes don't have any annotations applied to them.

Note: I haven't tested this with non-data classes, nor fields.

**Comment by pwall567** [comment] 2022-10-09 11:42
As with your other issue, I'm very sorry about the delay in responding.  But in this case, I'm struggling to see what the problem is.  Configuration like you have there works OK in most tests – can you give more information on the circumstances?  The schema and the generated output?

**Comment by pwall567** [comment] 2022-10-09 13:20
I've just noticed – your issue report specifically mentions version 0.81.  Annotations were added in version 0.82.  Are you using the correct version?

**Comment by Tzrlk** [comment] 2022-10-14 05:06
Well that's embarrassing. I'll double check things when I get home and update accordingly.

**Comment by pwall567** [comment] 2023-01-31 11:19
I'm closing this issue as resolved.  If you think there are still outstanding questions, feel free to reopen it or create a new issue.

**Closed by pwall567** 2023-01-31 11:19 UTC

**Comment by Tzrlk** [comment] 2023-01-31 23:37
Oh, I completely forgot about this. Yes, it's all good.
